### ISSUE TITLE
new name for this ezmaster app

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/ezmaster-automaton#1]
after talking with @parmentf , we think this app could be better named. We suggest to use "ezmaster-crontab", because actually, this application can launch any commands and not only ezmaster-auto-upgrade.

**Comment by touv** [comment]
or ezmaster-tweak like (ubuntu|unity|windows) tweak

**Comment by kerphi** [comment]
or ezmaster-plugin

**Comment by kerphi** [comment]
or ezmaster-tickler (chatouilleur :p)

**Comment by kerphi** [comment]
or ezmaster-cli-app

**Comment by touv** [comment]
@parmentf ton avis ?

**Comment by touv** [comment]
ezmaster-admin

**Comment by kerphi** [comment]
ezmaster-robot
ezmaster-bot
ezmaster-automaton

**Comment by kerphi** [comment]
ezmaster-refresher
ezmaster-upgrader

**Comment by kerphi** [comment]
ezmaster-gc
ezmaster-sweeper

**Comment by kerphi** [comment]
ezmaster-cleaner

**Comment by kerphi** [comment]
ezmaster-controller

**Comment by kerphi** [comment]
ezmaster-automaton is the winner!
